version: '3'

services:
  app:
    container_name: item-keeper-node
    restart: always
    build: .
    ports:
      - '80:8080'
    links:
      - item-keeper-mongo
  item-keeper-mongo:
    container_name: item-keeper-mongo
    image: mongo
    ports:
      - '27017:27017'